### ISSUE TITLE
candidate location requirements?

### ISSUE THREAD

**Issue by heyjawrsh** [carrot/we-are-hiring#10]
I've been digging around in your projects- roots got me in the door, someone talking about lots of free food kept me here ;) - and just found this repo. I've had nothing but respect for Vice since [TNBM](http://www.vice.com/video/true-norwegian-black-metal) showed up on what was then vbs.tv, and am now finding Carrot to be equally admirable- what, with all of the open source contributions and awesome articles/blogs. But in all seriousness: do you _really_ only hire candidates in Brooklyn or L.A.?

<3

**Comment by notslang** [comment]
Thanks for taking interest in us! As for location requirements: we only have offices in Brooklyn and L.A., but we _do_ have developers around the world. For example, @hhsnopek is in Wisconsin, @jenius is traveling around the world on "sabbatical" for a year, and @declandewet is in South Africa. So, even if you're in Texas it's worth applying. :smile:

**Comment by heyjawrsh** [comment]
That's fantastic! Thanks for that, @slang800.
