### ISSUE TITLE
broken link in `README.md`

### ISSUE THREAD

**Issue by rowe-morehouse** [carrot/we-are-hiring#8]
We've been `exploring` React + Flux …
links to:
https://github.com/carrot/roots-react-playground
404 to the floor :)

**Comment by BrandonRomano** [comment]
Hey @rowe-morehouse, thanks for the catch.

We currently have that as a private repo.  Obviously, we should either make the repo public or not link it in the README!

I'm not the one who's been playing around with that repo, so I'll let @kylemac make the decision of which way to go with this.

**Comment by rowe-morehouse** [comment]
Didn't mean to bust anyone!! ... just snooping. :)

**Comment by BrandonRomano** [comment]
Ha, no don't worry -- we appreciate it definitely!

**Comment by kylemac** [comment]
@rowe-morehouse open sourced now https://github.com/carrot/roots-react-playground
